name: Update Naver Blog JSON

on:
  schedule:
    # UTC 기준으로 매월 1일·15일 15:00에 실행 → 한국시간(KST) 매월 2일·16일 00:00
    - cron: '0 15 1,15 * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  crawl-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Create public directory if not exists
        run: |
          mkdir -p public/blog-data

      - name: Run crawler and write JSON
        run: |
          python scripts/fetch_blog.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/blog-data/post_list.json
          git diff --quiet && echo "No changes to commit" || git commit -m "chore: update naver blog JSON" 
          git push
